#!/usr/bin/env bash
# setup_ramdisk.sh
#
# Creates RAM-backed block devices for testing Timelock Drive without a
# physical disk.  Uses the Linux `brd` (block RAM disk) kernel module to
# expose one or more /dev/ramN devices.
#
# Usage:
#   sudo ./setup_ramdisk.sh [--size-gb N] [--count N] [--dev-mode] [--teardown]
#
# Options:
#   --size-gb N    Size of each RAM disk in GiB (default: 10, matching
#                  the PHYSICAL_DISK_SIZE compiled into the gatekeeper).
#                  Use --dev-mode for a smaller 1 GiB disk.
#   --count N      Number of RAM disks to create (default: 1).
#   --dev-mode     Shorthand for --size-gb 1. Suitable for quick testing
#                  on machines without 10 GiB of free RAM.
#   --teardown     Unload the brd module and destroy existing RAM disks.
#
# After running, the first RAM disk is printed to stdout.
# To point the gatekeeper at the RAM disk, either:
#   export GK_DISK_PATH=/dev/ram0
#   sudo -E ./gatekeeper/main-rust/target/release/main --timelockdrive --ipc
# or source the env file this script writes:
#   source /tmp/td_ramdisk.env && sudo -E <gatekeeper>
#
# NOTE: The default 10 GiB size requires ~10 GiB of free RAM.
# All data is lost when the module is unloaded or the system reboots.

set -euo pipefail

# ── defaults ─────────────────────────────────────────────────────────────────
SIZE_GB=10
COUNT=1
TEARDOWN=false
ENV_FILE=/tmp/td_ramdisk.env

# ── arg parsing ───────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case "$1" in
        --size-gb)  SIZE_GB="$2"; shift 2 ;;
        --count)    COUNT="$2";   shift 2 ;;
        --dev-mode) SIZE_GB=1;    shift   ;;
        --teardown) TEARDOWN=true; shift  ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

# ── helpers ──────────────────────────────────────────────────────────────────
info() { echo "[ramdisk] $*"; }
die()  { echo "[ramdisk] ERROR: $*" >&2; exit 1; }

[[ "$EUID" -eq 0 ]] || die "Must run as root (use sudo)."

# ── teardown ─────────────────────────────────────────────────────────────────
if $TEARDOWN; then
    info "Tearing down RAM disks..."
    if lsmod | grep -q '^brd '; then
        rmmod brd
        info "brd module unloaded; /dev/ram* devices removed."
    else
        info "brd module is not loaded, nothing to do."
    fi
    rm -f "$ENV_FILE"
    # Restore config file to physical disk default
    CONFIG_FILE="/etc/timelockdrive/gatekeeper.toml"
    if [[ -f "$CONFIG_FILE" ]]; then
        sed -i 's|^disk_path *=.*|disk_path = "/dev/sdb"|' "$CONFIG_FILE"
        info "Restored ${CONFIG_FILE}: disk_path = \"/dev/sdb\""
    fi
    exit 0
fi

# ── load brd module ───────────────────────────────────────────────────────────
SIZE_KB=$(( SIZE_GB * 1024 * 1024 ))   # brd uses KiB for rd_size

info "RAM disk size : ${SIZE_GB} GiB (${SIZE_KB} KiB per device)"
info "Number of disks: ${COUNT}"

if lsmod | grep -q '^brd '; then
    info "brd module already loaded."
    info "To change RAM disk size you must first run: sudo ./setup_ramdisk.sh --teardown"
else
    info "Loading brd kernel module..."
    modprobe brd "rd_nr=${COUNT}" "rd_size=${SIZE_KB}"
fi

# ── verify devices ────────────────────────────────────────────────────────────
FIRST_DEV=""
for i in $(seq 0 $(( COUNT - 1 ))); do
    DEV="/dev/ram${i}"
    if [[ ! -b "$DEV" ]]; then
        die "${DEV} not found after loading brd. Check kernel support with: modinfo brd"
    fi
    info "Device ready: ${DEV}  ($(( SIZE_KB / 1024 )) MiB)"
    if [[ -z "$FIRST_DEV" ]]; then
        FIRST_DEV="$DEV"
    fi
done

# ── write env file and update system config ───────────────────────────────────
cat > "$ENV_FILE" <<EOF
# Timelock Drive RAM disk environment
# Generated by setup_ramdisk.sh on $(date)
# Source this file before launching the gatekeeper:
#   source $ENV_FILE && sudo -E ./gatekeeper/main-rust/target/release/main --timelockdrive --ipc
export GK_DISK_PATH=${FIRST_DEV}
EOF

# Update /etc/timelockdrive/gatekeeper.toml if it exists
CONFIG_FILE="/etc/timelockdrive/gatekeeper.toml"
if [[ -f "$CONFIG_FILE" ]]; then
    # Replace the disk_path line in the config file
    sed -i "s|^disk_path *=.*|disk_path = \"${FIRST_DEV}\"|" "$CONFIG_FILE"
    info "Updated ${CONFIG_FILE}: disk_path = \"${FIRST_DEV}\""
fi

info ""
info "RAM disk ready.  To use:"
info ""
info "  source ${ENV_FILE}"
info "  sudo -E ./gatekeeper/gatekeeper/main-rust/target/release/main --timelockdrive --ipc"
info ""
info "Or inline:"
info "  GK_DISK_PATH=${FIRST_DEV} sudo -E ./gatekeeper/gatekeeper/main-rust/target/release/main --timelockdrive --ipc"
info ""
info "To destroy the RAM disks:  sudo ./setup_ramdisk.sh --teardown"
info ""
echo "${FIRST_DEV}"
