#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/test_lib_defaults.sh"
test_lib_init_shared_defaults "$SCRIPT_DIR"
source "$TESTS_DIR/test_lib_common.sh"
source "$TESTS_DIR/test_lib_transport.sh"
TMP_DIR="$(mktemp -d)"
test_lib_init_tmp_artifact_defaults "$TMP_DIR"

TEST_BLOCK_BASE="${TEST_BLOCK_BASE:-250000}"
NUM_WRITES="${NUM_WRITES:-10000}"
WRITE_BATCH_MAX="${WRITE_BATCH_MAX:-256}"
GK_TRACE_WRITES="${GK_TRACE_WRITES:-1}"
APPLY_GK_TRACE_PATCH="${APPLY_GK_TRACE_PATCH:-1}"

test_lib_setup_transport_from_env

gatekeeper_pid=""
gatekeeper_launcher_pid=""
driver_pid=""
bdus_device=""
test_succeeded=0

log() {
    printf '[e2e_seq] %s\n' "$*"
}

test_lib_setup_cleanup_trap

ensure_gatekeeper_trace_patch() {
    if [[ "$APPLY_GK_TRACE_PATCH" == "0" ]]; then
        log "Skipping autogenerated gatekeeper trace patch (APPLY_GK_TRACE_PATCH=0)"
        return 0
    fi

    if [[ -x "$VDIR/tests/ensure_gatekeeper_trace_patch.sh" ]]; then
        "$VDIR/tests/ensure_gatekeeper_trace_patch.sh" "$GK_MAIN_RS"
        return 0
    fi

    log "Trace patch utility missing; skipping patch step"
}

run_sequential_writes() {
    local issued=0
    local batch_max="$WRITE_BATCH_MAX"
    if [[ "$batch_max" -lt 1 ]]; then
        batch_max=1
    fi

    local max_payload_blocks="$batch_max"
    if [[ "$max_payload_blocks" -gt "$NUM_WRITES" ]]; then
        max_payload_blocks="$NUM_WRITES"
    fi
    if [[ "$max_payload_blocks" -lt 1 ]]; then
        max_payload_blocks=1
    fi

    local payload="$TMP_DIR/payload.bin"
    head -c "$((max_payload_blocks * 4096))" /dev/urandom >"$payload"

    log "Issuing $NUM_WRITES sequential writes in random multi-block batches (1..$batch_max) starting at lba=$TEST_BLOCK_BASE"
    while [[ "$issued" -lt "$NUM_WRITES" ]]; do
        local remaining=$((NUM_WRITES - issued))
        local batch=$((RANDOM % batch_max + 1))
        if [[ "$batch" -gt "$remaining" ]]; then
            batch="$remaining"
        fi

        local lba=$((TEST_BLOCK_BASE + issued))
        test_lib_run_with_timeout "$IO_TIMEOUT_SECS" \
            sudo dd if="$payload" of="$bdus_device" bs=4096 seek="$lba" count="$batch" conv=notrunc status=none
        issued=$((issued + batch))
    done

    test_lib_run_with_timeout "$IO_TIMEOUT_SECS" sudo sync
}

analyze_trace() {
    local raw_ranges="$TMP_DIR/gk_ranges_raw.txt"
    local run_labeled="$TMP_DIR/gk_ranges_runs.txt"
    local run_id_file="$TMP_DIR/gk_run_id.txt"
    local run_blocks_file="$TMP_DIR/gk_run_blocks.txt"
    local dominant_run="$TMP_DIR/gk_dominant_run.txt"
    local analysis="$TMP_DIR/seq_analysis.txt"

    awk '
    /^\[gk_trace\] recv_range\[/ {
        pba = -1;
        blocks = 0;
        if (match($0, /pba=[0-9]+/)) {
            pba = substr($0, RSTART + 4, RLENGTH - 4) + 0;
        }
        if (match($0, /blocks=[0-9]+/)) {
            blocks = substr($0, RSTART + 7, RLENGTH - 7) + 0;
        }
        if (pba >= 0) {
            if (blocks < 1) {
                blocks = 1;
            }
            print NR " " pba " " blocks;
        }
    }
    ' "$GATEKEEPER_LOG" >"$raw_ranges"

    local raw_count
    raw_count="$(wc -l <"$raw_ranges")"
    if [[ "$raw_count" -le 0 ]]; then
        log "No [gk_trace] range logs found; enable gatekeeper tracing with GK_TRACE_WRITES=1"
        echo "--- gatekeeper log tail ---"
        tail -n 80 "$GATEKEEPER_LOG" || true
        echo "--- driver trace tail (debug only) ---"
        tail -n 80 "$TRACE_FILE" || true
        return 1
    fi

    awk '
    {
        seq = $1;
        pba = $2;
        blocks = $3;
        if (NR == 1 || pba != prev_pba + prev_blocks) {
            run += 1;
        }
        run_tot[run] += blocks;
        print run " " seq " " pba " " blocks;
        prev_pba = pba;
        prev_blocks = blocks;
    }
    END {
        best_run = 0;
        best_blocks = 0;
        for (r in run_tot) {
            if (run_tot[r] > best_blocks) {
                best_blocks = run_tot[r];
                best_run = r;
            }
        }
        print best_run > run_id_path;
        print best_blocks > run_blocks_path;
    }
    ' run_id_path="$run_id_file" run_blocks_path="$run_blocks_file" "$raw_ranges" >"$run_labeled"

    local best_run
    best_run="$(cat "$run_id_file")"
    local best_blocks
    best_blocks="$(cat "$run_blocks_file")"

    awk -v run="$best_run" '$1 == run { print $0; }' "$run_labeled" >"$dominant_run"

    awk -v base="$TEST_BLOCK_BASE" '
    {
        lba = base + offset;
        pba = $3;
        blocks = $4;
        print lba " " pba " " blocks " 0 0";
        offset += blocks;
    }
    ' "$dominant_run" >"$analysis"

    if [[ "$best_blocks" -lt "$NUM_WRITES" ]]; then
        log "Dominant gatekeeper run too short: blocks=$best_blocks requested=$NUM_WRITES"
        echo "--- gatekeeper trace sample ---"
        head -n 80 "$raw_ranges"
        echo "--- driver trace tail (debug only) ---"
        tail -n 80 "$TRACE_FILE" || true
        return 1
    fi

    local found
    found="$(wc -l <"$analysis")"
    if [[ "$found" -le 0 ]]; then
        log "Expected captured writes in trace, but none were found"
        echo "--- analysis output ---"
        cat "$analysis"
        return 1
    fi

    local first_pba
    first_pba="$(head -n1 "$analysis" | awk '{print $2}')"
    local gap_count=0
    local explained_gap_count=0
    local unexplained_count=0
    local multi_block_count=0
    local mismatch_report="$TMP_DIR/seq_mismatch.txt"
    : >"$mismatch_report"

    local prev_lba=""
    local prev_pba=""
    local prev_blocks="1"
    local prev_dr=""
    local prev_md=""
    while read -r lba pba blocks dr md; do
        if [[ -z "$blocks" || "$blocks" -lt 1 ]]; then
            blocks=1
        fi
        if [[ "$blocks" -gt 1 ]]; then
            multi_block_count=$((multi_block_count + 1))
        fi
        if [[ -n "$prev_lba" ]]; then
            local delta
            delta=$((pba - prev_pba))
            if [[ "$delta" -gt 1 ]]; then
                gap_count=$((gap_count + 1))
            fi

            local expected
            expected=$((prev_pba + prev_blocks))
            if [[ "$pba" -ne "$expected" ]]; then
                unexplained_count=$((unexplained_count + 1))
                printf 'UNEXPLAINED prev_lba=%s prev_pba=%s prev_blocks=%s prev_data_ranges=%s prev_md_blocks=%s cur_lba=%s cur_pba=%s expected=%s\n' \
                    "$prev_lba" "$prev_pba" "$prev_blocks" "$prev_dr" "$prev_md" "$lba" "$pba" "$expected" >>"$mismatch_report"
            elif [[ "$prev_blocks" -gt 1 ]]; then
                explained_gap_count=$((explained_gap_count + 1))
                # printf 'GAP_EXPLAINED prev_lba=%s prev_pba=%s prev_blocks=%s prev_data_ranges=%s prev_md_blocks=%s cur_lba=%s cur_pba=%s\n' \
                    # "$prev_lba" "$prev_pba" "$prev_blocks" "$prev_dr" "$prev_md" "$lba" "$pba" >>"$mismatch_report"
            fi
        fi

        prev_lba="$lba"
        prev_pba="$pba"
        prev_blocks="$blocks"
        prev_dr="$dr"
        prev_md="$md"
    done <"$analysis"

    log "Sequential analysis summary: first_pba=$first_pba observed_entries=$found requested_writes=$NUM_WRITES multi_block_entries=$multi_block_count gaps(>1)=$gap_count explained_by_prev_blocks=$explained_gap_count unexplained=$unexplained_count"

    if [[ "$NUM_WRITES" -gt 1 && "$WRITE_BATCH_MAX" -gt 1 && "$multi_block_count" -eq 0 ]]; then
        log "Did not observe any multi-block write ranges; writeback may still be splitting to single-block I/O"
        echo "--- first captured pairs ---"
        head -n 40 "$analysis"
        return 1
    fi

    if [[ "$gap_count" -gt 0 ]]; then
        echo "--- gap classification (first 40) ---"
        head -n 40 "$mismatch_report"
    fi

    if [[ "$unexplained_count" -ne 0 ]]; then
        log "Detected unexplained non-sequential physical writes"
        echo "--- first captured pairs ---"
        head -n 20 "$analysis"
        return 1
    fi

    log "Sequential write behavior confirmed with explicit gap accounting"
}

analyze_md_amortization() {
    # Parse [gk_trace] recv_write lines which carry num_md_blocks and num_data_ranges.
    # For each write event compute blocks_per_md (infinity when md=0) and report:
    #   - total writes, total data blocks, total md blocks sent
    #   - writes with 0 md blocks (fully amortized)
    #   - writes with >=1 md block
    #   - mean/min/max data blocks per md block sent
    local analysis
    analysis="$(awk '
    /^\[gk_trace\] recv_write / {
        nb = 0; md = 0;
        for (i = 1; i <= NF; i++) {
            if ($i ~ /^num_data_ranges=/) nb = substr($i, 17) + 0;
            if ($i ~ /^num_md_blocks=/)   md = substr($i, 15) + 0;
        }
        total_writes++;
        total_md += md;
        if (md == 0) {
            zero_md_writes++;
        } else {
            nonzero_md_writes++;
            # accumulate data block count for this write from the following recv_range lines
        }
        pending_md = md;
        pending_ranges = nb;
        next;
    }
    /^\[gk_trace\] recv_range\[/ {
        blocks = 0;
        for (i = 1; i <= NF; i++) {
            if ($i ~ /^blocks=/) blocks = substr($i, 8) + 0;
        }
        if (pending_ranges > 0) {
            pending_data_blocks += blocks;
            pending_ranges--;
        }
        if (pending_ranges == 0 && pending_data_blocks > 0) {
            total_data_blocks += pending_data_blocks;
            if (pending_md > 0) {
                ratio = pending_data_blocks / pending_md;
                if (count_ratio == 0 || ratio < min_ratio) min_ratio = ratio;
                if (ratio > max_ratio) max_ratio = ratio;
                sum_ratio += ratio;
                count_ratio++;
            }
            pending_data_blocks = 0;
            pending_md = 0;
        }
        next;
    }
    END {
        printf "total_writes=%d total_data_blocks=%d total_md_blocks_sent=%d\n", total_writes, total_data_blocks, total_md;
        printf "writes_with_0_md=%d writes_with_md=%d\n", zero_md_writes, nonzero_md_writes;
        if (total_md > 0)
            printf "overall_data_blocks_per_md=%.2f\n", total_data_blocks / total_md;
        else
            printf "overall_data_blocks_per_md=inf (no md blocks sent)\n";
        if (count_ratio > 0)
            printf "per_write_data_blocks_per_md: mean=%.2f min=%.2f max=%.2f (over %d writes-with-md)\n", sum_ratio/count_ratio, min_ratio, max_ratio, count_ratio;
    }
    ' "$GATEKEEPER_LOG")"

    log "Metadata amortization report:"
    while IFS= read -r line; do
        log "  $line"
    done <<< "$analysis"
}

analyze_md_repeats() {
    # For each write (delimited by recv_write lines), collect the set of md_idx
    # values sent. Track how many times each md_idx appears across writes, and
    # report indices that were sent more than once (re-sent after already seen).
    local report
    report="$(awk '
    /^\[gk_trace\] recv_write / {
        in_write = 1;
        next;
    }
    in_write && /^\[gk_trace\] recv_md / {
        md = -1;
        for (i = 1; i <= NF; i++) {
            if ($i ~ /^md_idx=/) md = substr($i, 8) + 0;
        }
        if (md >= 0) {
            total_sends++;
            send_count[md]++;
            if (send_count[md] == 2) first_repeat_write[md] = total_sends;
        }
        next;
    }
    /^\[gk_trace\] recv_write / || !/^\[gk_trace\]/ { in_write = 0; }
    END {
        repeats = 0;
        for (md in send_count) {
            if (send_count[md] > 1) repeats++;
        }
        total_md_indices = length(send_count);
        printf "distinct_md_indices_seen=%d md_indices_resent=%d total_md_sends=%d\n",
               total_md_indices, repeats, total_sends;
        if (repeats > 0) {
            printf "resent_indices (md_idx: send_count):\n";
            for (md in send_count) {
                if (send_count[md] > 1)
                    printf "  md_idx=%d sent=%d\n", md, send_count[md];
            }
        }
    }
    ' "$GATEKEEPER_LOG")"

    log "Metadata repeat-send report:"
    while IFS= read -r line; do
        log "  $line"
    done <<< "$report"
}

log "Building gatekeeper and host driver"
ensure_gatekeeper_trace_patch
test_lib_build_gatekeeper_if_needed 'cd "$GDIR/gatekeeper/main-rust" && cargo build --release'
(
    cd "$VDIR"
    make versioning_td_driver
)

test_lib_preflight_cleanup_full "$IO_TIMEOUT_SECS" log
sudo sh -c ": > '$TRACE_FILE'"
test_lib_start_gatekeeper 1 1 1
test_lib_start_driver "default"
run_sequential_writes
analyze_trace
analyze_md_amortization
analyze_md_repeats

test_succeeded=1
log "PASS: sequential write test completed"
