#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/test_lib_defaults.sh"
test_lib_init_shared_defaults "$SCRIPT_DIR"
source "$TESTS_DIR/test_lib_common.sh"
source "$TESTS_DIR/test_lib_transport.sh"
TMP_DIR="$(mktemp -d)"
test_lib_init_tmp_artifact_defaults "$TMP_DIR"

TEST_BLOCK_BASE="${TEST_BLOCK_BASE:-250000}"
NUM_WRITES="${NUM_WRITES:-10000}"
WRITE_BATCH_MAX="${WRITE_BATCH_MAX:-256}"
RECOVERY_WINDOW_WRITES="${RECOVERY_WINDOW_WRITES:-256}"
SYNC_EVERY_WRITES="${SYNC_EVERY_WRITES:-0}"
GK_TRACE_WRITES="${GK_TRACE_WRITES:-1}"
APPLY_GK_TRACE_PATCH="${APPLY_GK_TRACE_PATCH:-1}"

test_lib_setup_transport_from_env

gatekeeper_pid=""
driver_pid=""
bdus_device=""
test_succeeded=0

test_lib_setup_cleanup_trap

log() {
    printf '[e2e_seq_sync] %s\n' "$*"
}

clean_gk_shutdown() {
    test_lib_clean_gk_shutdown gatekeeper_pid "" driver_pid bdus_device "$IO_TIMEOUT_SECS" log
}

# Cleanup is handled by test_lib_setup_cleanup_trap


start_gatekeeper() {
    test_lib_start_gatekeeper_raw "" "$@"
}

ensure_gatekeeper_trace_patch() {
    if [[ "$APPLY_GK_TRACE_PATCH" == "0" ]]; then
        log "Skipping autogenerated gatekeeper trace patch (APPLY_GK_TRACE_PATCH=0)"
        return 0
    fi

    if [[ -x "$VDIR/tests/ensure_gatekeeper_trace_patch.sh" ]]; then
        "$VDIR/tests/ensure_gatekeeper_trace_patch.sh" "$GK_MAIN_RS"
        return 0
    fi

    log "Trace patch utility missing; skipping patch step"
}

run_sequential_writes_with_sync_points() {
    local issued=0
    local did_mid_sync=0
    local sync_after=$((NUM_WRITES / 2))
    local sync_every="$SYNC_EVERY_WRITES"
    local next_sync_at=0
    local sync_count=0
    local sync_points_file="$TMP_DIR/sync_points.txt"
    : >"$sync_points_file"
    local batch_max="$WRITE_BATCH_MAX"

    if [[ "$batch_max" -lt 1 ]]; then
        batch_max=1
    fi

    if [[ "$sync_after" -lt 1 ]]; then
        sync_after=1
    fi

    if [[ "$sync_every" -lt 0 ]]; then
        sync_every=0
    fi

    if [[ "$sync_every" -gt 0 ]]; then
        next_sync_at="$sync_every"
    fi

    local max_payload_blocks="$batch_max"
    if [[ "$max_payload_blocks" -gt "$NUM_WRITES" ]]; then
        max_payload_blocks="$NUM_WRITES"
    fi
    if [[ "$max_payload_blocks" -lt 1 ]]; then
        max_payload_blocks=1
    fi

    local payload="$TMP_DIR/payload.bin"
    head -c "$((max_payload_blocks * 4096))" /dev/urandom >"$payload"

    if [[ "$sync_every" -gt 0 ]]; then
        log "Issuing $NUM_WRITES sequential writes in random batches (1..$batch_max) with periodic sync every $sync_every writes"
    else
        log "Issuing $NUM_WRITES sequential writes in random batches (1..$batch_max) with one sync after $sync_after writes"
    fi

    while [[ "$issued" -lt "$NUM_WRITES" ]]; do
        local remaining=$((NUM_WRITES - issued))
        local batch=$((RANDOM % batch_max + 1))
        if [[ "$batch" -gt "$remaining" ]]; then
            batch="$remaining"
        fi

        if [[ "$sync_every" -gt 0 ]]; then
            if [[ "$next_sync_at" -gt 0 && "$issued" -lt "$next_sync_at" && $((issued + batch)) -gt "$next_sync_at" ]]; then
                batch=$((next_sync_at - issued))
                if [[ "$batch" -lt 1 ]]; then
                    batch=1
                fi
            fi
        else
            if [[ "$did_mid_sync" -eq 0 && "$issued" -lt "$sync_after" && $((issued + batch)) -gt "$sync_after" ]]; then
                batch=$((sync_after - issued))
                if [[ "$batch" -lt 1 ]]; then
                    batch=1
                fi
            fi
        fi

        local lba=$((TEST_BLOCK_BASE + issued))
        test_lib_run_with_timeout "$IO_TIMEOUT_SECS" \
            sudo dd if="$payload" of="$bdus_device" bs=4096 seek="$lba" count="$batch" conv=notrunc status=none
        issued=$((issued + batch))

        if [[ "$sync_every" -gt 0 ]]; then
            if [[ "$next_sync_at" -gt 0 && "$issued" -ge "$next_sync_at" ]]; then
                log "Issuing periodic sync at write_index=$issued"
                test_lib_run_with_timeout "$IO_TIMEOUT_SECS" sudo sync "$bdus_device"
                printf '%s\n' "$issued" >>"$sync_points_file"
                sync_count=$((sync_count + 1))
                next_sync_at=$((next_sync_at + sync_every))
                if [[ "$next_sync_at" -gt "$NUM_WRITES" ]]; then
                    next_sync_at=0
                fi
            fi
        else
            if [[ "$did_mid_sync" -eq 0 && "$issued" -ge "$sync_after" ]]; then
                log "Issuing mid-stream sync at write_index=$issued"
                test_lib_run_with_timeout "$IO_TIMEOUT_SECS" sudo sync "$bdus_device"
                printf '%s\n' "$issued" >>"$sync_points_file"
                sync_count=$((sync_count + 1))
                did_mid_sync=1
            fi
        fi
    done

    test_lib_run_with_timeout "$IO_TIMEOUT_SECS" sudo sync "$bdus_device"

    if [[ "$sync_count" -eq 0 ]]; then
        printf '%s\n' "$sync_after" >>"$sync_points_file"
        sync_count=1
    fi

    echo "$sync_count" >"$TMP_DIR/sync_count.txt"
}

analyze_trace() {
    local raw_ranges="$TMP_DIR/gk_ranges_raw.txt"
    local run_labeled="$TMP_DIR/gk_ranges_runs.txt"
    local run_id_file="$TMP_DIR/gk_run_id.txt"
    local run_blocks_file="$TMP_DIR/gk_run_blocks.txt"
    local dominant_run="$TMP_DIR/gk_dominant_run.txt"
    local analysis="$TMP_DIR/seq_sync_analysis.txt"
    local sync_points_file="$TMP_DIR/sync_points.txt"
    local sync_count
    sync_count="$(cat "$TMP_DIR/sync_count.txt")"

    # In short runs (especially NUM_WRITES=1), give gatekeeper logs a brief
    # moment to settle so trailing metadata writes are visible before parsing.
    local prev_range_count=-1
    local stable_iters=0
    for _ in $(seq 1 25); do
        local cur_range_count
        cur_range_count="$(rg -c '^\[gk_trace\] recv_range\[' "$GATEKEEPER_LOG" 2>/dev/null || echo 0)"
        if [[ "$cur_range_count" -eq "$prev_range_count" ]]; then
            stable_iters=$((stable_iters + 1))
            if [[ "$stable_iters" -ge 3 ]]; then
                break
            fi
        else
            stable_iters=0
            prev_range_count="$cur_range_count"
        fi
        sleep 0.1
    done

    awk '
    /^\[gk_trace\] recv_range\[/ {
        pba = -1;
        blocks = 0;
        if (match($0, /pba=[0-9]+/)) {
            pba = substr($0, RSTART + 4, RLENGTH - 4) + 0;
        }
        if (match($0, /blocks=[0-9]+/)) {
            blocks = substr($0, RSTART + 7, RLENGTH - 7) + 0;
        }
        if (pba >= 0) {
            if (blocks < 1) {
                blocks = 1;
            }
            print NR " " pba " " blocks;
        }
    }
    ' "$GATEKEEPER_LOG" >"$raw_ranges"

    local raw_count
    raw_count="$(wc -l <"$raw_ranges")"
    if [[ "$raw_count" -le 0 ]]; then
        log "No [gk_trace] range logs found; enable gatekeeper tracing with GK_TRACE_WRITES=1"
        echo "--- gatekeeper log tail ---"
        tail -n 80 "$GATEKEEPER_LOG" || true
        echo "--- driver trace tail (debug only) ---"
        tail -n 80 "$TRACE_FILE" || true
        return 1
    fi

    awk '
    {
        seq = $1;
        pba = $2;
        blocks = $3;
        if (NR == 1 || pba != prev_pba + prev_blocks) {
            run += 1;
        }
        run_tot[run] += blocks;
        print run " " seq " " pba " " blocks;
        prev_pba = pba;
        prev_blocks = blocks;
    }
    END {
        best_run = 0;
        best_blocks = 0;
        for (r in run_tot) {
            if (run_tot[r] > best_blocks) {
                best_blocks = run_tot[r];
                best_run = r;
            }
        }
        print best_run > run_id_path;
        print best_blocks > run_blocks_path;
    }
    ' run_id_path="$run_id_file" run_blocks_path="$run_blocks_file" "$raw_ranges" >"$run_labeled"

    local best_run
    best_run="$(cat "$run_id_file")"
    local best_blocks
    best_blocks="$(cat "$run_blocks_file")"

    awk -v run="$best_run" '$1 == run { print $0; }' "$run_labeled" >"$dominant_run"

    local selected_stream="$dominant_run"
    local selected_note="dominant_run"
    if [[ "$NUM_WRITES" -le 1 || "$SYNC_EVERY_WRITES" -gt 0 || "$NUM_WRITES" -gt 1 ]]; then
        # One-write probes, periodic-sync runs, and single-mid-sync runs all
        # intentionally include metadata writes or sync-induced address
        # discontinuities; use the full stream to preserve those transitions.
        selected_stream="$run_labeled"
        selected_note="full_stream"
    fi

    awk -v base="$TEST_BLOCK_BASE" '
    {
        lba = base + offset;
        pba = $3;
        blocks = $4;
        print lba " " pba " " blocks " 0 0";
        offset += blocks;
    }
    ' "$selected_stream" >"$analysis"

    if [[ "$selected_note" == "dominant_run" && "$NUM_WRITES" -gt 1 && "$best_blocks" -lt "$NUM_WRITES" ]]; then
        log "Dominant gatekeeper run too short: blocks=$best_blocks requested=$NUM_WRITES"
        echo "--- gatekeeper trace sample ---"
        head -n 80 "$raw_ranges"
        echo "--- driver trace tail (debug only) ---"
        tail -n 80 "$TRACE_FILE" || true
        return 1
    fi

    local found
    found="$(wc -l <"$analysis")"
    if [[ "$selected_note" == "dominant_run" && "$NUM_WRITES" -gt 1 && "$found" -le 1 ]]; then
        log "Expected multiple captured writes in trace, but found $found"
        echo "--- analysis output ---"
        cat "$analysis"
        return 1
    fi

    local first_pba
    first_pba="$(head -n1 "$analysis" | awk '{print $2}')"

    local mismatch_report="$TMP_DIR/seq_sync_mismatch.txt"
    local gap_inversion_report="$TMP_DIR/seq_sync_gap_inversion_all.txt"
    : >"$mismatch_report"
    : >"$gap_inversion_report"

    local gap_count=0
    local explained_gap_count=0
    local unexplained_count=0
    local gap_inversion_count=0
    local multi_block_count=0
    local before_sync_unexplained=0
    local in_sync_window_unexplained=0
    local after_sync_tail_unexplained=0

    local sync_points=()
    while read -r point; do
        if [[ -n "$point" ]]; then
            sync_points+=("$point")
        fi
    done <"$sync_points_file"

    local prev_lba=""
    local prev_pba=""
    local prev_blocks="1"
    local prev_dr=""
    local prev_md=""

    while read -r lba pba blocks dr md; do
        if [[ -z "$blocks" || "$blocks" -lt 1 ]]; then
            blocks=1
        fi
        if [[ "$blocks" -gt 1 ]]; then
            multi_block_count=$((multi_block_count + 1))
        fi

        if [[ -n "$prev_lba" ]]; then
            local delta
            delta=$((pba - prev_pba))
            if [[ "$delta" -gt 1 ]]; then
                gap_count=$((gap_count + 1))
            fi

            local expected
            expected=$((prev_pba + prev_blocks))

            if [[ "$pba" -ne "$expected" ]]; then
                local kind="GAP"
                if [[ "$pba" -lt "$expected" ]]; then
                    kind="INVERSION"
                fi

                local sync_scope="before_sync"
                for sync_point in "${sync_points[@]}"; do
                    local sync_lba_boundary=$((TEST_BLOCK_BASE + sync_point))
                    local recovery_boundary_lba=$((sync_lba_boundary + RECOVERY_WINDOW_WRITES))
                    if [[ "$lba" -ge "$sync_lba_boundary" && "$lba" -lt "$recovery_boundary_lba" ]]; then
                        sync_scope="sync_window"
                        break
                    elif [[ "$lba" -ge "$recovery_boundary_lba" ]]; then
                        sync_scope="after_sync_window"
                    fi
                done

                printf '%s prev_lba=%s prev_pba=%s prev_blocks=%s prev_data_ranges=%s prev_md_blocks=%s cur_lba=%s cur_pba=%s expected=%s delta=%s sync_scope=%s\n' \
                    "$kind" "$prev_lba" "$prev_pba" "$prev_blocks" "$prev_dr" "$prev_md" "$lba" "$pba" "$expected" "$((pba - expected))" "$sync_scope" >>"$gap_inversion_report"
                gap_inversion_count=$((gap_inversion_count + 1))
            fi

            if [[ "$pba" -ne "$expected" ]]; then
                unexplained_count=$((unexplained_count + 1))

                local is_after_any_sync=0
                local is_in_sync_window=0
                for sync_point in "${sync_points[@]}"; do
                    local sync_lba_boundary=$((TEST_BLOCK_BASE + sync_point))
                    local recovery_boundary_lba=$((sync_lba_boundary + RECOVERY_WINDOW_WRITES))
                    if [[ "$lba" -ge "$sync_lba_boundary" ]]; then
                        is_after_any_sync=1
                    fi
                    if [[ "$lba" -ge "$sync_lba_boundary" && "$lba" -lt "$recovery_boundary_lba" ]]; then
                        is_in_sync_window=1
                        break
                    fi
                done

                if [[ "$is_after_any_sync" -eq 0 ]]; then
                    before_sync_unexplained=$((before_sync_unexplained + 1))
                elif [[ "$is_in_sync_window" -eq 1 ]]; then
                    in_sync_window_unexplained=$((in_sync_window_unexplained + 1))
                else
                    after_sync_tail_unexplained=$((after_sync_tail_unexplained + 1))
                fi

                printf 'UNEXPLAINED prev_lba=%s prev_pba=%s prev_blocks=%s prev_data_ranges=%s prev_md_blocks=%s cur_lba=%s cur_pba=%s expected=%s\n' \
                    "$prev_lba" "$prev_pba" "$prev_blocks" "$prev_dr" "$prev_md" "$lba" "$pba" "$expected" >>"$mismatch_report"
            elif [[ "$prev_blocks" -gt 1 ]]; then
                explained_gap_count=$((explained_gap_count + 1))
                # printf 'GAP_EXPLAINED prev_lba=%s prev_pba=%s prev_blocks=%s prev_data_ranges=%s prev_md_blocks=%s cur_lba=%s cur_pba=%s\n' \
                #     "$prev_lba" "$prev_pba" "$prev_blocks" "$prev_dr" "$prev_md" "$lba" "$pba" >>"$mismatch_report"
            fi
        fi

        prev_lba="$lba"
        prev_pba="$pba"
        prev_blocks="$blocks"
        prev_dr="$dr"
        prev_md="$md"
    done <"$analysis"

    log "Sync-injected sequential summary: source=$selected_note first_pba=$first_pba observed_entries=$found requested_writes=$NUM_WRITES sync_count=$sync_count sync_every_writes=$SYNC_EVERY_WRITES recovery_window=$RECOVERY_WINDOW_WRITES multi_block_entries=$multi_block_count gaps(>1)=$gap_count explained_by_prev_blocks=$explained_gap_count unexplained_total=$unexplained_count unexplained_before_sync=$before_sync_unexplained unexplained_in_sync_window=$in_sync_window_unexplained unexplained_after_sync_tail=$after_sync_tail_unexplained"

    if [[ "$gap_inversion_count" -gt 0 ]]; then
        log "Printing all detected gap/inversion transitions ($gap_inversion_count total)"
        cat "$gap_inversion_report"
    fi

    if [[ "$NUM_WRITES" -gt 1 && "$WRITE_BATCH_MAX" -gt 1 && "$multi_block_count" -eq 0 ]]; then
        log "Did not observe any multi-block write ranges; writeback may still be splitting to single-block I/O"
        echo "--- first captured pairs ---"
        head -n 100 "$analysis"
        return 1
    fi

    if [[ "$before_sync_unexplained" -ne 0 ]]; then
        log "Detected unexplained non-sequential writes before sync"
        echo "--- gap classification (first 100) ---"
        head -n 100 "$mismatch_report"
        return 1
    fi

    if [[ "$after_sync_tail_unexplained" -ne 0 ]]; then
        log "Note: $after_sync_tail_unexplained unexplained gap(s) beyond recovery window (expected from metadata log block interleaving)"
        echo "--- gap classification (first 100) ---"
        head -n 100 "$mismatch_report"
    fi

    if [[ "$in_sync_window_unexplained" -gt 0 ]]; then
        log "Observed transient unexplained writes inside recovery window after sync (allowed); verifying steady-state recovery succeeded"
        echo "--- gap classification (first 100) ---"
        head -n 100 "$mismatch_report"
    fi

    log "Sequential write behavior with mid-sync recovered to steady state"
}

log "Building gatekeeper and host driver"
analyze_md_amortization() {
    local analysis
    analysis="$(awk '
    /^\[gk_trace\] recv_write / {
        nb = 0; md = 0;
        for (i = 1; i <= NF; i++) {
            if ($i ~ /^num_data_ranges=/) nb = substr($i, 17) + 0;
            if ($i ~ /^num_md_blocks=/)   md = substr($i, 15) + 0;
        }
        total_writes++;
        total_md += md;
        if (md == 0) { zero_md_writes++; } else { nonzero_md_writes++; }
        pending_md = md;
        pending_ranges = nb;
        next;
    }
    /^\[gk_trace\] recv_range\[/ {
        blocks = 0;
        for (i = 1; i <= NF; i++) {
            if ($i ~ /^blocks=/) blocks = substr($i, 8) + 0;
        }
        if (pending_ranges > 0) {
            pending_data_blocks += blocks;
            pending_ranges--;
        }
        if (pending_ranges == 0 && pending_data_blocks > 0) {
            total_data_blocks += pending_data_blocks;
            if (pending_md > 0) {
                ratio = pending_data_blocks / pending_md;
                if (count_ratio == 0 || ratio < min_ratio) min_ratio = ratio;
                if (ratio > max_ratio) max_ratio = ratio;
                sum_ratio += ratio;
                count_ratio++;
            }
            pending_data_blocks = 0;
            pending_md = 0;
        }
        next;
    }
    END {
        printf "total_writes=%d total_data_blocks=%d total_md_blocks_sent=%d\n", total_writes, total_data_blocks, total_md;
        printf "writes_with_0_md=%d writes_with_md=%d\n", zero_md_writes, nonzero_md_writes;
        if (total_md > 0)
            printf "overall_data_blocks_per_md=%.2f\n", total_data_blocks / total_md;
        else
            printf "overall_data_blocks_per_md=inf (no md blocks sent)\n";
        if (count_ratio > 0)
            printf "per_write_data_blocks_per_md: mean=%.2f min=%.2f max=%.2f (over %d writes-with-md)\n", sum_ratio/count_ratio, min_ratio, max_ratio, count_ratio;
    }
    ' "$GATEKEEPER_LOG")"

    log "Metadata amortization report:"
    while IFS= read -r line; do
        log "  $line"
    done <<< "$analysis"
}

analyze_md_repeats() {
    local report
    report="$(awk '
    /^\[gk_trace\] recv_write / {
        in_write = 1;
        next;
    }
    in_write && /^\[gk_trace\] recv_md / {
        md = -1;
        for (i = 1; i <= NF; i++) {
            if ($i ~ /^md_idx=/) md = substr($i, 8) + 0;
        }
        if (md >= 0) {
            total_sends++;
            send_count[md]++;
        }
        next;
    }
    /^\[gk_trace\] recv_write / || !/^\[gk_trace\]/ { in_write = 0; }
    END {
        repeats = 0;
        for (md in send_count) {
            if (send_count[md] > 1) repeats++;
        }
        printf "distinct_md_indices_seen=%d md_indices_resent=%d total_md_sends=%d\n",
               length(send_count), repeats, total_sends;
        if (repeats > 0) {
            printf "resent_indices (md_idx: send_count):\n";
            for (md in send_count) {
                if (send_count[md] > 1)
                    printf "  md_idx=%d sent=%d\n", md, send_count[md];
            }
        }
    }
    ' "$GATEKEEPER_LOG")"

    log "Metadata repeat-send report:"
    while IFS= read -r line; do
        log "  $line"
    done <<< "$report"
}

log "Building gatekeeper and host driver"
ensure_gatekeeper_trace_patch
test_lib_build_gatekeeper_if_needed 'cd "$GDIR/gatekeeper/main-rust" && cargo build --release'
(
    cd "$VDIR"
    make versioning_td_driver
)

test_lib_preflight_cleanup_full "$IO_TIMEOUT_SECS" log
sudo sh -c ": > '$TRACE_FILE'"
start_gatekeeper
test_lib_start_driver "initial"
run_sequential_writes_with_sync_points
analyze_trace
analyze_md_amortization
analyze_md_repeats

test_succeeded=1
log "PASS: sync-injected sequential write test completed"
